"""UI contracts and app-tool services used by launcher presentation layers."""

from .app_tools import (
    AppToolAction,
    AppToolActionResult,
    AppToolService,
    SystemTerminalAdapter,
    TerminalAdapter,
    TerminalCommand,
)
from .log_filter import (
    FILTER_WARNING_STANDALONE_BANG,
    FilteredLine,
    HighlightRange,
    LogFilterResult,
    LogFilterResultState,
    LogFilterSpec,
    apply_log_filter,
    highlight_ranges,
    parse_filter_expression,
)
from .log_reader import (
    DEFAULT_MAX_BYTES,
    DEFAULT_TAIL_LINES,
    MAX_READ_BYTES,
    MAX_TAIL_LINES,
    MIN_READ_BYTES,
    MIN_TAIL_LINES,
    BoundedLogReader,
    LogChangeKind,
    LogReader,
    LogSnapshot,
    LogSnapshotState,
    classify_log_change,
)

__all__ = [
    "AppToolAction",
    "AppToolActionResult",
    "AppToolService",
    "SystemTerminalAdapter",
    "TerminalAdapter",
    "TerminalCommand",
    "FILTER_WARNING_STANDALONE_BANG",
    "FilteredLine",
    "HighlightRange",
    "LogFilterResult",
    "LogFilterResultState",
    "LogFilterSpec",
    "apply_log_filter",
    "highlight_ranges",
    "parse_filter_expression",
    "DEFAULT_MAX_BYTES",
    "DEFAULT_TAIL_LINES",
    "MAX_READ_BYTES",
    "MAX_TAIL_LINES",
    "MIN_READ_BYTES",
    "MIN_TAIL_LINES",
    "BoundedLogReader",
    "LogChangeKind",
    "LogReader",
    "LogSnapshot",
    "LogSnapshotState",
    "classify_log_change",
]
